global:
  scrape_interval: 5s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
